# -*- coding: utf-8 -*-
"""Quiz#004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDHiPxXsaw2VH4awtxulVwH1hmeayZ-C
"""

def perfectN(num):
  factors=[]
  for i in range (1, num ):
    if num %i == 0: 
      factors.append(i)
  return factors
  for item in factors:
    item += item
    if item == number:
      return True
    else:
      return False
print(perfectN(6))
print(perfectN(10))