# -*- coding: utf-8 -*-
"""Quiz#001

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDHiPxXsaw2VH4awtxulVwH1hmeayZ-C
"""

def Makes20(A,B):
    if A==20 or B==20 or A+B==20:
      statement = True
    else:
      statement = False
    return statement
print(Makes20(9,20))
print(Makes20(9,9))
print(Makes20(11,9))