# -*- coding: utf-8 -*-
"""Quiz#004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lrQRoOUpuCUuabMTBocRMcBUCeDG19rC
"""

def tableM(N):
    for y in range(1,10):
        print(str(N)+"X"+str(y)+"="+str(int(N)*y))
    
tableM(2)