# -*- coding: utf-8 -*-
"""Quiz#003

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxZ8DCIImXB2u4cLu2VFd4yxILALqXZL
"""

def quiz003(N):
  S=0
  t=0
  result=""
  for y in range(100):
    for i in range(N):
      t+=1
      if t<=100:
        if t==100:
          result+=str(i)
        else:
          result+=str(i) +", "
        S+=i
      else:
        break
  print(result) 
  print("The addition of the numbers is: " + str(S))
quiz003(3)
quiz003(5)